### ISSUE TITLE
Interface SHOULD support notifications (void functions)

### ISSUE THREAD

**Issue by giefferre** [coopernurse/barrister#6]
As described in the official [specification](http://www.jsonrpc.org/specification#notification), JSON-RPC 2.0 does support Notifications.

> A Notification is a Request object without an "id" member. A Request object that is a Notification signifies the Client's lack of interest in the corresponding Response object, and as such no Response object needs to be returned to the client. **The Server MUST NOT reply to a Notification, including those that are within a batch request.**

> Notifications are not confirmable by definition, since **they do not have a Response object to be returned.** As such, the Client would not be aware of any errors (like e.g. "Invalid params","Internal error").

In fact, Barrister does not support notifications, but it should.

@coopernurse is there any reason about this choice?

/cc @devalecs and @brunobellissimo who are working with me using barrister

**Comment by coopernurse** [comment]
Thanks for doing this work and I agree that it should be supported.

Barrister has a conformance test suite that I use to ensure that all the language bindings interoperate uniformly.  It would be good to add a notification function call to the IDL that's used by these tests.

Since this IDL grammar change should be backwards compatible I'm not sure that we need to update the conformance suite before merging this PR, but I'd like to think about it a bit.

It's currently a bit challenging to get the test suite to run, and this is a great use case for Docker.  Let me know if you or your team has interest in assisting me in getting some Dockerfiles written.  I'll open separate issues for that work, but since this is the first major outside contribution to barrister it's the first time I've had an immediate need for other developers to run that suite.

Thanks

**Comment by coopernurse** [comment]
The other consideration for this PR is that language bindings that have code generators (currently Java and Go) will need to be updated to support this.  Currently those code generators expect return values for all functions.

Not a huge piece of work, but again, another thing to consider before merging the PR.

**Comment by giefferre** [comment]
Thanks for your comments :)

Are you referencing the `idl_parse_test.sh` file? It now includes a new test IDL (cf. https://github.com/coopernurse/barrister/pull/7/files#diff-e4cb8358b3e34f6fb636c55b8bfe721fR1)

Anyway, about the conformance test / suite: in our humble opinion it would be great to switch to Travis CI, which supports Docker natively and has a free plan for public repos. I can support you in the switch, of course.

About the language bindings, I can help you with the code generator written in Go. Please provide me with all the pieces of information I need to start.

For further details we can have a quick chat using http://gitter.im, but you have to create the chatroom since you are the repo's owner :)

**Comment by coopernurse** [comment]
Thanks for your comments.  I've created a gitter room and added the badge to the barrister README:

https://gitter.im/coopernurse/barrister

I've also created a ticket to discuss the migration of the conformance tests to Docker:

https://github.com/coopernurse/barrister/issues/8
